```{r}
mtcars[1,10]
mtcars[2,]
mtcars[,2]
mtcars[1,2:5]
mtcars[1, c(2,6,8)]

#o seed tem que ser setado a cada geração de numeros aleatorios
set.seed(1)
rnorm(5)
set.seed(1)
rnorm(5)
rnorm(5)

set.seed(1)
amostra = c( "T", "R", "I", "A", "N", "G", "U","L", "O", "S")
sample(x = amostra, replace = FALSE)
sample(x = amostra, replace = TRUE)
sample(x = amostra, size = 5)
sample(x = amostra, size = 10, replace = FALSE, prob = c(1, 1, 5, 1, 1, 1, 1, 1, 1, 5))

#amostragem probabilistica aleatoria simples
sample.int(n = 2, size = 6, replace = TRUE)

n <- nrow(mtcars)
n
index <- sample.int(n, 30)
amostraAleatoria <- mtcars[index,]
amostraAleatoria

#amostragem probailistica sistematica. Sorteio baseado em uma estratégia. Ex : Selecionar a cada 10
mtcars
mtcarsIndex <- mtcars %>% mutate(id = 1:nrow(mtcars))
mtcarsIndex
##Amostrando a cada 10 carros
index <- seq(10, nrow(mtcarsIndex), by = 10)
index
amostraSistematica <- mtcars[index,]
amostraSistematica

#amostragem probailistica estratificada. Sorteio de indivíduos dentro dos estratos
mtcarsAutomatic <- mtcars %>% filter(am == 1)
mtcarsManual <- mtcars %>% filter(am == 0)

##amostrando 7 carros de cada tipo
idAutomatic <- sample.int(nrow(mtcarsAutomatic), 7)
idManual <- sample.int(nrow(mtcarsManual), 7)

amostraAutomatic <- mtcarsAutomatic[idAutomatic,]
amostraManual <- mtcarsManual[idManual,]

bind_rows(amostraAutomatic, amostraManual)

#amostragem probailistica conglomeradas. Sorteio de clusters e não dos indivíduos.
#Criando Artificialmente 50 clusters (conglomerados)
mtcarsCluster <- mtcars %>% mutate(cluster = sample.int(12, nrow(mtcars), replace = TRUE))
mtcarsCluster
idcluster <- mtcarsCluster$cluster %>% unique()
idcluster

#amostrando 3 clusters
amostraid <- sample(x = idcluster, size = 3, replace = FALSE)
amostraCluster <- mtcarsCluster %>% dplyr::filter(cluster %in% amostraid)
amostraCluster

#Vamos criar uma base de treino com 70% dos dados
n <- nrow(mtcars)
index <- sample.int(n, 0.7 * n)
index
treino <- mtcars[index,]
teste <- mtcars[-index,]
treino 
teste

#usando dplyr
treino <- mtcarsIndex %>% sample_frac(0.7)
teste <- dplyr::anti_join(mtcarsIndex, treino, by = 'id')
teste
```
```{r}
#Exercicios
sim.dat <- read.csv("http://bit.ly/2P5gTw4")
```


```{r}
#amostragem aleatoria simples
qtdeLinhas <- nrow(sim.dat)
qtdeLinhas

index <- sample.int(qtdeLinhas, 400, replace = FALSE)
index

sim.dat[index,]
```
```{r}
#amostragem aleatoria estratificada
segmentPrice <- filter(sim.dat, segment == "Price" & !is.na(sim.dat$segment))
segmentConspicuous <- filter(sim.dat, segment == "Conspicuous" & !is.na(sim.dat$segment))
segmentQuality <- filter(sim.dat, segment == "Quality" & !is.na(sim.dat$segment))
segmentStyle <- filter(sim.dat, segment == "Style" & !is.na(sim.dat$segment))

linhasPrice <- nrow(segmentPrice)
linhasConspicuous <- nrow(segmentConspicuous)
linhasQuality <- nrow(segmentQuality)
linhasStyle <- nrow(segmentStyle)

set.seed(1234)
indexPrice = sample.int(linhasPrice, 100)

set.seed(1234)
indexConspicuous = sample.int(linhasConspicuous, 100)

set.seed(1234)
indexQuality = sample.int(linhasQuality, 100)

set.seed(1234)
indexStyle = sample.int(linhasStyle, 100)

amostraPrice <- segmentPrice[indexPrice,]
amostraConspicuous <- segmentConspicuous[indexConspicuous,]
amostraQuality <- segmentQuality[indexQuality,]
amostraStyle <- segmentStyle[indexStyle,]

amostraEstratificada <- bind_rows(amostraPrice, amostraConspicuous, amostraQuality, amostraStyle)
amostraEstratificada

#ouuuuuuuu
set.seed(1234)
amostraPrice <- segmentPrice[sample.int(nrow(filter(sim.dat, segment == "Price" & !is.na(sim.dat$segment))), 100),]

set.seed(1234)
amostraConspicuous <- segmentConspicuous[sample.int(nrow(filter(sim.dat, segment == "Conspicuous" & !is.na(sim.dat$segment))), 100),]

set.seed(1234)
amostraQuality <- segmentQuality[sample.int(nrow(filter(sim.dat, segment == "Quality" & !is.na(sim.dat$segment))), 100),]

set.seed(1234)
amostraStyle <- segmentStyle[sample.int(nrow(filter(sim.dat, segment == "Style" & !is.na(sim.dat$segment))), 100),]

amostraEstratificada <- bind_rows(amostraPrice, amostraConspicuous, amostraQuality, amostraStyle)
amostraEstratificada

amostraEstratificada %>% ggplot +  geom_boxplot(aes(x = segment, y = store_exp))

amostraConspicuous %>% arrange(store_exp)
```

