--Tabela que armazena os dados dos clientes
CREATE TABLE "Cliente" (
  "IdCliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NomeCliente" varchar,
  "CPF" varchar,
  "RG" varchar,
  "DataNascimento" datetime
);

--Tabela que armazena os endereços dos clientes
CREATE TABLE "Endereco" (
  "IdEndereco" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdCliente" integer,
  "Logradouro" varchar,
  "Numero" varchar,
  "Complemento" varchar,
  "PontoReferencia" varchar
);

--Tabela que armazena os telefones dos clientes
CREATE TABLE "Telefone" (
  "IdTelefone" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdCliente" integer,
  "DDD" integer,
  "Telefone" integer
);

--Tabela que armazena todas as agencias
CREATE TABLE "Agencia" (
  "IdAgencia" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NomeAgencia" varchar
);

--Tabela de armazena as categorias de conta
CREATE TABLE "CategoriaConta" (
  "IdCategoriaConta" integer PRIMARY KEY,
  "NomeCategoriaConta" varchar
);

--Tabela que armazena as contas 
CREATE TABLE "Conta" (
  "IdConta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdCliente" integer,
  "IdAgencia" integer,
  "IdCategoriaConta" integer,
  "NumeroConta" integer
);

--Tabela que armazena os tipos de operação
CREATE TABLE "TipoOperacao" (
  "IdTipoOperacao" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NomeOperacao" varchar
);

--Tabela que armazena todas as operações realizadas
CREATE TABLE "Operacao" (
  "IdOperacao" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdTipoOperacao" integer,
  "IdConta" integer,
  "CreditoDebito" varchar(1),
  "DataOperacao" datetime,
  "Valor" numeric(15,2),
  "Status" varchar(1),
  "BancoDestino" integer,
  "AgenciaDestino" integer,
  "ContaDestino" integer,
  "CpfCnpjDestino" varchar
);

--Tabela que armazena os produtos
CREATE TABLE "Produto" (
  "IdProduto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NomeProduto" varchar,
  "InicioVigencia" datetime,
  "FimVigencia" datetime
);

--Tabela que armazena os contratos de credito
CREATE TABLE "ContratoCredito" (
  "IdContrato" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdProduto" integer,
  "IdConta" integer,
  "DataContratacao" datetime,
  "ValorContratado" numeric(15,2),
  "ValorFinal" numeric(15,2),
  "Taxas" nueric(15,2)
);

--Tabela que armazena as parcelas dos contratos de credito
CREATE TABLE "ParcelasContatoCredito" (
  "IdContrato" integer,
  "NumeroParcela" integer,
  "Valor" numeric(15,2),
  "Status" varchar(2),
  PRIMARY KEY ("IdContrato", "NumeroParcela")
);

--Adicionando comentario na coluna "CreditoDebito" da tabela "Operacao"
COMMENT ON COLUMN "Operacao"."CreditoDebito" IS 'C para crédito e D para débito';

--Adicionando comentario na coluna "Status" da tabela "Operacao"
COMMENT ON COLUMN "Operacao"."Status" IS 'P - Pendente, E - Efetivada, C - Cancelada';

--Adicionando comentario na coluna "Status" da tabela "ParcelasContatoCredito"
COMMENT ON COLUMN "ParcelasContatoCredito"."Status" IS 'PG - Pago, NP - Nao Pago, CL - Cancelado';

--Criando relação entre as tabelas "Cliente" e "Endereco"
ALTER TABLE "Cliente" ADD FOREIGN KEY ("IdCliente") REFERENCES "Endereco" ("IdCliente");

--Criando relação entre as tabelas "Cliente" e "Telefone"
ALTER TABLE "Cliente" ADD FOREIGN KEY ("IdCliente") REFERENCES "Telefone" ("IdCliente");

--Criando relação entre as tabelas "Cliente" e "Conta"
ALTER TABLE "Cliente" ADD FOREIGN KEY ("IdCliente") REFERENCES "Conta" ("IdCliente");

--Criando relação entre as tabelas "Conta" e "Agencia"
ALTER TABLE "Conta" ADD FOREIGN KEY ("IdAgencia") REFERENCES "Agencia" ("IdAgencia");

--Criando relação entre as tabelas "Conta" e "CategoriaConta"
ALTER TABLE "Conta" ADD FOREIGN KEY ("IdCategoriaConta") REFERENCES "CategoriaConta" ("IdCategoriaConta");

--Criando relação entre as tabelas "Operacao" e "Conta"
ALTER TABLE "Operacao" ADD FOREIGN KEY ("IdConta") REFERENCES "Conta" ("IdConta");

--Criando relação entre as tabelas "Operacao" e "TipoOperacao"
ALTER TABLE "Operacao" ADD FOREIGN KEY ("IdTipoOperacao") REFERENCES "TipoOperacao" ("IdTipoOperacao");

--Criando relação entre as tabelas "Produto" e "ContratoCredito"
ALTER TABLE "Produto" ADD FOREIGN KEY ("IdProduto") REFERENCES "ContratoCredito" ("IdProduto");

--Criando relação entre as tabelas "ContratoCredito" e "Conta"
ALTER TABLE "ContratoCredito" ADD FOREIGN KEY ("IdConta") REFERENCES "Conta" ("IdConta");

--Criando relação entre as tabelas "ParcelasContatoCredito" e "ContratoCredito"
ALTER TABLE "ParcelasContatoCredito" ADD FOREIGN KEY ("IdContrato") REFERENCES "ContratoCredito" ("IdContrato");

